Fix GKE GCloud Auth Plugin Instalation

diff --git a/.github/workflows/bad.yml b/.github/workflows/bad.yml
--- a/.github/workflows/bad.yml
+++ b/.github/workflows/bad.yml
@@ -38,22 +38,27 @@ jobs:
           docker push ssobol/notes-backend:latest
 
       # Step 5: Install the GKE GCloud Auth Plugin
-      - name: Install Google Cloud SDK and Auth Plugin
+      - name: Install Google Cloud SDK and GKE Auth Plugin
         run: |
-          sudo apt-get update
-          sudo apt-get install -y apt-transport-https ca-certificates gnupg
-          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
-          sudo apt-get update && sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin
-          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
-          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $HOME/.bashrc
+          # Add the Google Cloud public key
+          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
+            
+          # Add the Google Cloud SDK repository
+          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
+            
+            # Update and install the required packages
+            sudo apt-get update
+            sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin
+            
+            # Configure the environment variable
+            export USE_GKE_GCLOUD_AUTH_PLUGIN=True
+            echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $HOME/.bashrc
 
 
       - name: Validate GKE GCloud Auth Plugin Installation
         run: |
-            which gke-gcloud-auth-plugin || echo "Plugin not found"
-            gke-gcloud-auth-plugin --version || echo "Unable to verify version"
-        
+          which gke-gcloud-auth-plugin || echo "Plugin not found"
+          gke-gcloud-auth-plugin --version || echo "Unable to verify version"
 
       # Step 5: Set up Google Cloud authentication for GKE (use if using GKE)
       - name: Authenticate to Google Cloud
